# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0002_auto_20170710_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fails', models.IntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algo_id', models.ManyToManyField(related_name='algoAlgos', to='algo.Algo')),
                ('userJoin', models.ManyToManyField(related_name='userAlgos', to='algo.User')),
            ],
        ),
    ]
