# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0004_auto_20170711_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralgo',
            name='userJoin',
        ),
        migrations.AddField(
            model_name='useralgo',
            name='userJoin',
            field=models.ManyToManyField(related_name='userAlgos', to='algo.User'),
        ),
    ]
