# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0005_auto_20170711_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralgo',
            name='algo_id',
        ),
        migrations.AddField(
            model_name='useralgo',
            name='algo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='algoAlgos', to='algo.Algo'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='useralgo',
            name='userJoin',
        ),
        migrations.AddField(
            model_name='useralgo',
            name='userJoin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userAlgos', to='algo.User'),
            preserve_default=False,
        ),
    ]
