# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0007_algo_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='algo',
            name='second_solution',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='algo',
            name='solution_explanation',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='algo',
            name='solution_hint',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='algo',
            name='solution',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
