# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0008_auto_20170714_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algo',
            old_name='solution_explanation',
            new_name='explanation',
        ),
        migrations.RenameField(
            model_name='algo',
            old_name='solution_hint',
            new_name='hint',
        ),
    ]
